config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'

  get '/register', to: 'users#new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users, only: [:create]
  resources :lists, except: [:new, :edit]
  resources :items, only: [:create, :update, :destroy]
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :list
end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :user
  has_many :items

  def total_cost
    total = items.reduce(0) { |acc, elem| acc + (elem.price || 0) }
    ActiveSupport::NumberHelper.number_to_currency(total)
  end

  def items_remaining
    items.size - items.select(&:completed).size
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :lists

  has_secure_password

  validates :username, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :logged_in?

  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_login
    unless logged_in?
      flash[:error] = "You must be logged in to do that."
      redirect_to login_path
    end
  end

  def require_owner(model, id)
    record = model.find(id)

    unless logged_in? && (record.user == current_user)
      flash[:error] = "You don't have permission to do that."
      redirect_to login_path
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :_set_item, only: [:update, :destroy]
  before_action :_set_list

  def create
    @item = Item.create(_item_params.merge(completed: false))
  end

  def update
    if params.keys.include? "completed"
      @item.update(completed: params[:completed])
    else
      @item.update(_item_params)
    end
  end

  def destroy
    @item.destroy
  end

  private

  def _item_params
    params.require(:item).permit(:name, :price, :quantity, :list_id)
  end

  def _set_item
    @item = Item.find(params[:id])
  end

  def _set_list
    @list = List.find(params[:list_id] || params[:item][:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :require_login, only: [:index, :create]

  before_action only: [:show, :update, :destroy] do
    require_owner(List, params[:id])
  end

  before_action :_set_list, only: [:show, :update, :destroy]

  def index
    @lists = List.where(user: current_user)
    @new_list = List.new
  end

  def show
    @items = @list.items
    @new_item = Item.new
  end

  def create
    @list = List.new(_list_params)
    @list.user = current_user
    @list.save
  end

  def update
    @list.update(_list_params)
  end

  def destroy
    @list.destroy
  end

  private

  def _list_params
    params.require(:list).permit(:name)
  end

  def _set_list
    @list = List.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to lists_path if logged_in?
  end

  def create
    user = User.find_by(username: params[:username])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:success] = "Glad to have you back #{user.username}!"
      redirect_to lists_path
    else
      flash[:error] = "Hmmm... Those credentials don't look valid."
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "See you again soon!"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(_user_params)

    if @user.save
      flash[:sucess] = "Welcome! You've got a shiny new account."
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def _user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  ERROR_COLOR = "red darken-4".freeze
  SUCCESS_COLOR = "green darken-1".freeze
  BUTTON_CLASS = "btn waves-effect waves-light".freeze

  def get_flash_color(name)
    if name == "error"
      ERROR_COLOR
    else
      SUCCESS_COLOR
    end
  end
end

app/views/items/_add_item.html.erb
<!-- Parameters: list, item -->

<li>
  <div class="collapsible-header">
    <i class="material-icons">add</i>Add Item
  </div>

  <div class="collapsible-body">
    <span>
      <%= render "items/form", list: list, item: item %>
    </span>
  </div>
</li>

app/views/items/_form.html.erb
<!-- Parmaters: list, item -->

<%= form_for item, remote: true do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true %>

  <div class="row">
    <div class="col s6">
      <%= f.label :price %>
      $<%= f.number_field :price, step: 0.01, required: true %>
    </div>

    <div class="col s6">
      <%= f.label :quantity %>
      <%= f.text_field :quantity, required: true %>
    </div>
  </div>

  <%= f.hidden_field :list_id, value: list.id %>

  <%= f.submit class: ApplicationHelper::BUTTON_CLASS %>
<% end %>

app/views/items/_item.html.erb
<!-- Parameters: list, item -->

<% item_id = "item-#{item.id}" %>

<li id="<%= item_id %>" class="<%= "completed" if item.completed %>">
  <div class="collapsible-header">
    <%= link_to (render "shared/icon", name: "check"),
                item_path(item, completed: !item.completed, list_id: list.id),
                method: :patch,
                remote: true %>

    <strong><%= item.name %> - </strong>
    <%= item.quantity %> |
    <%= number_to_currency(item.price) %>

    <%= link_to (render "shared/icon", name: "delete"),
                item_path(item, list_id: list.id),
                method: :delete,
                remote: true,
                class: "right" %>
  </div>
  <div class="collapsible-body">
    <span>
      <%= render "items/form", list: list, item: item %>
    </span>
  </div>
</li>

<script>
  // Binds to "complete" and "delete" buttons.
  $("#<%= item_id %>").find("a").on("click", function(event) {
    event.preventDefault();
    event.stopPropagation();

    $(this).trigger("click.rails");
  });
</script>

app/views/items/create.js.erb
var $list = $("#list-items");
var item_html = "<%= escape_javascript render('item', list: @list, item: @item) %>";

$list.append(item_html);

$("#new_item")[0].reset();

$("#total-cost").html("<%= @list.total_cost %>");
$("#items-remaining").html("<%= @list.items_remaining %>");

app/views/items/destroy.js.erb
$("#item-<%= @item.id %>").remove();

$("#total-cost").html("<%= @list.total_cost %>");
$("#items-remaining").html("<%= @list.items_remaining %>");

app/views/items/update.js.erb
var new_item_html = "<%= escape_javascript render('item', list: @list, item: @item) %>"

$("#item-<%= @item.id %>").replaceWith(new_item_html)

$("#total-cost").html("<%= @list.total_cost %>");
$("#items-remaining").html("<%= @list.items_remaining %>");

app/views/layouts/_flash_messages.html.erb
<% flash.each do |name, message| %>
  <% color = get_flash_color(name) %>

  <%= render "shared/card", content: message, color: color %>
<% end %>

app/views/layouts/_nav_items.html.erb
<% if logged_in? %>
  <li><%= link_to "My Lists", lists_path %></li>
  <li><%= link_to "Log out", logout_path, method: :delete %></li>
<% else %>
  <li><%= link_to "Log in", login_path %></li>
  <li><%= link_to "Register", register_path %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<nav>
  <div class="container">
    <a href="/" class="brand-logo">ShoppingMeyster</a>

    <ul class="hide-on-med-and-down right">
      <%= render "layouts/nav_items" %>
    </ul>

    <a href="#" data-activates="mobile-nav" class="button-collapse right">
      <%= render "shared/icon", name: "menu" %>
    </a>

    <ul id="mobile-nav" class="side-nav">
      <%= render "layouts/nav_items" %>
    </ul>
  </div>
</nav>

<script>
  $(document).ready(function() {
    $(".button-collapse").sideNav();
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShoppingMeyster</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'https://fonts.googleapis.com/icon?family=Material+Icons' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <%= render "layouts/navigation" %>
  </header>

  <main>
    <div class="container">
      <div>
        <%= render "layouts/flash_messages" %>
      </div>

      <%= yield %>
    </div>
  </main>
</body>
</html>

app/views/lists/_add_list.html.erb
<!-- Parameters: list -->

<li>
  <div class="collapsible-header">
    <i class="material-icons">add</i>Add List
  </div>

  <div class="collapsible-body">
    <span>
      <%= render "form", list: list %>
    </span>
  </div>
</li>

app/views/lists/_form.html.erb
<!-- Parameters: list -->

<%= form_for list, remote: true do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true %>

  <%= f.submit class: ApplicationHelper::BUTTON_CLASS %>
<% end %>

app/views/lists/_list.html.erb
<!-- Parameters: list -->

<% list_id = "list-#{list.id}" %>

<li id="<%= list_id %>">
  <div class="collapsible-header">
    <%= render "shared/icon", name: "toc" %>
    <strong><%= link_to list.name, list_path(list) %></strong>
    <span class="right">
      <%= link_to (render "shared/icon",
                  name: "delete"),
                  list_path(list),
                  method: :delete,
                  data: {
                    confirm: "Are you sure you want to delete this list?"
                  },
                  remote: true %>
    </span>
  </div>
  <div class="collapsible-body">
    <span>
      <%= render "form", list: list %>
    </span>
  </div>
</li>

<script>
  // Link to actual list.
  $("#<%= list_id %>").find("a").not("[data-remote=true]").on("click", function(event) {
    // TODO: This interferes with turbolinks (I believe) and is really slowing down going to this link.
    event.stopPropagation();
  });

  // Delete button.
  $("#<%= list_id %>").find("a[data-remote=true]").not().on("click", function(event) {
    event.preventDefault();
    event.stopPropagation();

    $(this).trigger("click.rails");
  });
</script>

app/views/lists/create.js.erb
var new_list_html = "<%= escape_javascript render('list', list: @list) %>";

$("#lists").append(new_list_html);
$("#new_list")[0].reset();

app/views/lists/destroy.js.erb
$("#list-<%= @list.id %>").remove();

app/views/lists/index.html.erb
<h1>Your Lists</h1>

<ul id="lists" class="collapsible popout" data-collapsible="expandable">
  <%= render "add_list", list: @new_list %>

  <% @lists.each do |list| %>
    <%= render "list", list: list %>
  <% end %>
</ul>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>

<ul id="list-items" class="collapsible popout" data-collapsible="expandable">
  <%= render "items/add_item", list: @list, item: @new_item %>

  <% @items.each do |item| %>
    <%= render "items/item", list: @list, item: item %>
  <% end %>
</ul>

<footer class="page-footer">
  <div class="container">
    <div class="row white-text">
      <span>
        Total Cost: <span id="total-cost"><%= @list.total_cost %></span>
      </span>
      <span class="right">
        Items Left: <span id="items-remaining"><%= @list.items_remaining %></span>
      </span>
    </div>
  </div>
</footer>

app/views/lists/update.js.erb
$("#list-<%= @list.id %>").replaceWith("<%= escape_javascript render('list', list: @list) %>");

app/views/shared/_card.html.erb
<!-- Parameters: color, content -->

<div class="row">
  <div class="col s12 m8 offset-m2">
    <div class="card-panel <%= color %>">
      <span class="white-text"><%= content %></span>
    </div>
  </div>
</div>

app/views/shared/_icon.html.erb
<!-- Parameters: size (optional), name -->

<% size ||= nil %>

<i class="<%= size %> material-icons"><%= name %></i>

app/views/users/new.html.erb
<h1>Register</h1>

<% if @user.errors.any? %>
  <% @user.errors.full_messages.each do |message| %>
    <%= render "shared/card", content: message, color: ApplicationHelper::ERROR_COLOR %>
  <% end %>
<% end %>

<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation, "Confirm Password" %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Register", class: ApplicationHelper::BUTTON_CLASS %>
<% end %>

<p>Already have an account? <%= link_to "Login here.", login_path %></p>